theme: jekyll-theme-minimal
title: JellyScrub
logo: city_logo.jpg
photography_url: flickr.com/slootus
rightcommute_url: rightcommute.co.uk
instagram_url: instagram.com/slothus
description: Be soft, but ready to sting.